name: Build Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ github.ref_name }}
            * Download the .exe file for Windows machines
            * Download the .bin file for Linux machines 
            * No support for OS X/MacOS. I don't have a Mac to test on...

  build:
    needs: [ create_release ]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Update_Seamless_Coop.bin
            asset_name: Update_Seamless_Coop.bin
          - os: windows-latest
            artifact_name: Update_Seamless_Coop.exe
            asset_name: Update_Seamless_Coop.exe
          
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: |
          python -m PyInstaller Update_Seamless_Coop.py --onefile --name ${{ matrix.artifact_name }} 

      - name: Upload File to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          file: dist/${{ matrix.artifact_name }} 
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }} 
