name: Create Python Executables

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          upload_exe_with_name: Update_Seamless_Coop.bin
          options: --onefile, --name Update_Seamless_Coop.bin
          
  build_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          upload_exe_with_name: Update_Seamless_Coop.exe
          options: --onefile, --name Update_Seamless_Coop.exe
          
